---
version: "3"

services:
  validator:
    container_name: validator
    image: mysten/sui-node:18e23a4790560aa10fb6c128744d162fda10b1c3
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=debug,narwhal=debug,narwhal-primary::helper=info
    labels:
      org.label-schema.name: "validator"
    ports:
      - "8080:8080"
      - "8081:8081/udp"
      - "8082:8082/udp"
      - "8084:8084/udp"
      - "9184:9184"
    network_mode: "host"
    volumes:
      - ./validator.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis.blob:/opt/sui/config/genesis.blob:ro
      - ../genesis/key-pairs:/opt/sui/key-pairs/:ro
      - suidb:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure

volumes:
  suidb:
